#pragma once
#include <iostream>

#define SCREEN_FPS 60.0f
#define SCREEN_TICKS_PER_FRAME (1.0f / SCREEN_FPS)

#define SCREEN_WIDTH 800
#define SCREEN_HEIGHT 600

const std::string MENU_BG = "MENU_BG";
const std::string LEVEL1_BG = "LEVEL1_BG";
const std::string LEVEL2_BG = "LEVEL2_BG";
const std::string PLAYER_SPRITE = "PLAYER_SPRITE";
const std::string PLAY_TEXT_SCORE_PLAYER1 = "PLAY_TEXT_SCORE_PLAYER1";
const std::string MENU_TEXT_BUTTON_LEVEL1 = "MENU_TEXT_BUTTON_LEVEL1";
const std::string MENU_TEXT_BUTTON_LEVEL2 = "MENU_TEXT_BUTTON_LEVEL2";
const std::string MENU_TEXT_BUTTON_RANKING = "MENU_TEXT_BUTTON_RANKING";
const std::string MENU_TEXT_BUTTON_DISABLESOUND = "MENU_TEXT_BUTTON_DISABLESOUND";
const std::string MENU_TEXT_BUTTON_ENABLESOUND = "MENU_TEXT_BUTTON_ENABLESOUND";
const std::string MENU_TEXT_BUTTON_EXIT = "MENU_TEXT_BUTTON_EXIT";

const std::string MENU_TEXT_BUTTON_LEVEL1_HOVER = "MENU_TEXT_BUTTON_LEVEL1_HOVER";
const std::string MENU_TEXT_BUTTON_LEVEL2_HOVER = "MENU_TEXT_BUTTON_LEVEL2_HOVER";
const std::string MENU_TEXT_BUTTON_RANKING_HOVER = "MENU_TEXT_BUTTON_RANKING_HOVER";
const std::string MENU_TEXT_BUTTON_DISABLESOUND_HOVER = "MENU_TEXT_BUTTON_DISABLESOUND_HOVER";
const std::string MENU_TEXT_BUTTON_ENABLESOUND_HOVER = "MENU_TEXT_BUTTON_ENABLESOUND_HOVER";
const std::string MENU_TEXT_BUTTON_EXIT_HOVER = "MENU_TEXT_BUTTON_EXIT_HOVER";

const std::string PATH_IMG = "../res/img/";
const std::string PATH_FONT = "../res/ttf/";
const std::string PATH_AU = "../res/au/";

const std::string SAIYAN = "SAIYAN";
const std::string GAME_OVER = "GAME_OVER";


